"""Add gender and user_type columns to users

Revision ID: 7145986cbd70
Revises: 
Create Date: 2025-06-28 10:20:41.977277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7145986cbd70'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('gender', sa.Enum('MALE', 'FEMALE', name='genderenum'), nullable=True))
    op.add_column('users', sa.Column('user_type', sa.Enum('HEARING', 'DEAF_MUTE', name='usertypeenum'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'user_type')
    op.drop_column('users', 'gender')
    # ### end Alembic commands ###
